# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [ ]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
res = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
res[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
print(res[:, 1:].mean(axis=0))
print(res[:, 1:].min(axis=0))
print(res[:, 1:].max(axis=0))
print(np.median(res[:, 1:], axis=0))

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
qt = np.quantile(res[:, 1], 0.75)
res[:, 1] = np.clip(res[:, 1], 0, qt)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
print(res[res[:, 1] == 0].shape[0])
res[res[:, 1] == 0, 1] = 1
res

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
len(np.unique(res[:, 0]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
answ = np.unique(res[:, 2])
len(answ), answ

(37, array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39], dtype=int32))

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
mas = res[res[:, 2] <= 5]
mas

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
ings_per_minute = res[:, 2] / res[:, 1]
average_ings_per_minute = np.mean(ings_per_minute)
max_ings_per_minute = np.amax(ings_per_minute)
average_ings_per_minute, max_ings_per_minute

(0.3983000355850672, 24.0)

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
res[res[:, 1].argsort()][-100:][:, 2].mean()

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
random_indexes = np.random.randint(0, len(res), 10)
res[random_indexes]

array([[287001,     61,      7],
       [434110,     15,      6],
       [356279,     55,     14],
       [233194,     65,      7],
       [173682,     65,     11],
       [128107,     50,      6],
       [270005,      5,      5],
       [218625,     50,     17],
       [113152,     30,     12],
       [145249,     65,      5]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
average_ings = res[:, 2].mean()
print(res[res[:, 2] < average_ings].shape[0] / len(res) *100, '%')

58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
simple = np.logical_and(res[:, 1] <= 20, res[:, 2] <= 5)[:, np.newaxis]
simple = simple.astype(int)
res_simple_column = np.column_stack((res, simple))
res_simple_column

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [ ]:
print(len(res_simple_column[res_simple_column[:, 3] == 1]) / len(res_simple_column[:, 3]) *100, '%')

9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
short_r = res[res[:, 1] < 10]
standart_r = res[(res[:, 1]>=10) & (res[:, 1]<20)]
long_r = res[res[:, 1] >= 20]
stop = min(len(short_r), len(standart_r), len(long_r))
groups = np.array([short_r[:stop], standart_r[:stop], long_r[:stop]])
groups.shape

(3, 7588, 3)